

data_sources = {
    'global': [
        {'url': 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv',
         'type': 'csv',
         'desc': 'Global confirmed cases',
         'source': 'Johns Hopkins CSSE',
         'country': 'World',
         'title': 'Confirmed',
         'output': 'global-covid-confirmed', 'isClean': True},
        {'url': 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv',
         'type': 'csv',
         'desc': 'Global deaths',
         'source': 'Johns Hopkins CSSE',
         'country': 'World',
         'title': 'Deaths',
         'output': 'global-covid-deaths', 'isClean': True},
        {'url': 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv',
         'type': 'csv',
         'desc': 'Global recovered cases',
         'source': 'Johns Hopkins CSSE',
         'country': 'World',
         'title': 'Recovered',
         'output': 'global-covid-recovered', 'isClean': True},
    ],
    'sp': [
        {'url': 'https://covid19.isciii.es/resources/serie_historica_acumulados.csv',
         'type': 'csv',
         'desc': 'Cases by date and Region (Infected, Hospitalized, Intensive Care Unit & Deaths)',
         'source': 'Instituto de Salud Carlos III',
         'country': 'Spain',
         'output': 'sp-covid-region', 'isClean': False},
        {'url': 'https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_casos.csv',
         'type': 'csv',
         'desc': 'Cases by date and Region',
         'source': '',
         'country': 'Spain',
         'output': 'sp-covid-areas', 'isClean': True},
    ],
    'us': [
        {'url': 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv',
         'type': 'csv',
         'desc': 'Cases at County-level',
         'source': 'New York Times',
         'country': 'United States',
         'output': 'us-covid-counties', 'isClean': True},
        {'url': 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv',
         'type': 'csv',
         'desc': 'Cases at State-level',
         'source': 'New York Times',
         'country': 'United States',
         'output': 'us-covid-states', 'isClean': True},
    ],
    'uk': [
        {'url': 'https://raw.githubusercontent.com/tomwhite/covid-19-uk-data/master/data/covid-19-cases-uk.csv',
         'type': 'csv',
         'desc': 'Cases by date, County and Area',
         'source': '',
         'country': 'United Kingdom',
         'output': 'uk-covid-area', 'isClean': False},
        {'url': 'https://coronavirus.data.gov.uk/downloads/csv/coronavirus-cases_latest.csv',
         'type': 'csv',
         'desc': 'Cases by date and different levels of aggregation',
         'source': '',
         'country': 'United Kingdom',
         'output': 'uk-covid-gov', 'isClean': True},
    ],
}


countries = data_sources.keys()
